package DataMahasiswa;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muh. Fathul Haqqi
 */
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;

public class dataMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    Connection con = null;
    public dataMahasiswa() {
        initComponents();
        con = KoneksiDB.getKoneksi();
        ShowData(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private ResultSet mhswa;
    private String sql="";
    private String nma="",nrp="",kls="";
    private int smt;
    
    private void clear(){
    tfnrp.setText("");
    tfnama.setText("");
    tfkelas.setText("");
    tfsemester.setText("");
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        tfnama = new javax.swing.JTextField();
        tfnrp = new javax.swing.JTextField();
        tfkelas = new javax.swing.JTextField();
        tfsemester = new javax.swing.JTextField();
        tbsimpan = new javax.swing.JButton();
        tbdelete = new javax.swing.JButton();
        tbupdate = new javax.swing.JButton();
        tbcari = new javax.swing.JButton();
        tbrefres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setText("Nama");

        jLabel2.setText("NRP");

        jLabel3.setText("Kelas");

        jLabel4.setText("Semester");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "NRP", "Kelas", "Semester"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tfnama.setText("jTextField1");

        tfnrp.setText("jTextField2");

        tfkelas.setText("jTextField3");

        tfsemester.setText("jTextField4");

        tbsimpan.setText("Simpan");
        tbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbsimpanActionPerformed(evt);
            }
        });

        tbdelete.setText("Delete");
        tbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbdeleteActionPerformed(evt);
            }
        });

        tbupdate.setText("Update");
        tbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbupdateActionPerformed(evt);
            }
        });

        tbcari.setText("Cari");
        tbcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbcariActionPerformed(evt);
            }
        });

        tbrefres.setText("Refresh");
        tbrefres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrefresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfsemester))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(43, 43, 43)
                                        .addComponent(tfnrp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(39, 39, 39)
                                        .addComponent(tfkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tbsimpan)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbrefres))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tbcari)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbupdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbdelete))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbdelete)
                    .addComponent(tbupdate)
                    .addComponent(tbcari))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbrefres)
                    .addComponent(tbsimpan))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbsimpanActionPerformed
        nma=String.valueOf(tfnama.getText());
        nrp=String.valueOf(tfnrp.getText());
        kls=String.valueOf(tfkelas.getText());
        smt=Integer.parseInt(tfsemester.getText());
        
        try{
            sql = "INSERT INTO mahasiswa (nama,nrp,kelas,semester) VALUES "
                    + "('" + nma + "','" + nrp + "','" + kls + "'," + smt + ")";

            Statement st=con.createStatement();
            st.execute(sql);
            clear();
            ShowData(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error \n Data Gagal Disimpan"+e.getMessage());
        }
    }//GEN-LAST:event_tbsimpanActionPerformed

    private void tbrefresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrefresActionPerformed
    clear();
    ShowData(null); 
    }//GEN-LAST:event_tbrefresActionPerformed

    private void tbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbupdateActionPerformed
        try{
        String sql = "UPDATE mahasiswa SET nama=?, kelas=?, semester=? WHERE nrp=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, tfnama.getText());
        pst.setString(2, tfkelas.getText());
        pst.setString(3, tfsemester.getText());
        pst.setString(4, tfnrp.getText().trim());

        pst.executeUpdate();

        ShowData(null);  // <--- ini untuk refresh table
        JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_tbupdateActionPerformed

    private void tbcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbcariActionPerformed
        try {
        con = KoneksiDB.getKoneksi();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM mahasiswa WHERE nrp='" + tfnrp.getText() + "'");
        
        if (rs.next()) {
            tfnama.setText(rs.getString("nama"));
            tfkelas.setText(rs.getString("kelas"));
            tfsemester.setText(rs.getString("semester"));
            JOptionPane.showMessageDialog(null, "Data ditemukan");
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
    }
    }//GEN-LAST:event_tbcariActionPerformed

    private void tbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbdeleteActionPerformed
        try{
        String sql = "DELETE FROM mahasiswa WHERE nrp=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, tfnrp.getText().trim());
        pst.executeUpdate();

        ShowData(null); // Wajib supaya tabel GUI refresh ulang
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        clear();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_tbdeleteActionPerformed

private void ShowData(String sql){
    DefaultTableModel data = new DefaultTableModel();
   data.addColumn("No");
   data.addColumn("Nama");
   data.addColumn("NRP");
   data.addColumn("Kelas");
   data.addColumn("Semester");

   try{
       int i=1;
       if (con == null){
           con = KoneksiDB.getKoneksi(); // ini juga harus diberi 'con ='
       }
       Statement st=con.createStatement();
       mhswa=st.executeQuery("select * from mahasiswa");
       while (mhswa.next()){
           data.addRow(new Object[]{
               i++,
               mhswa.getString("nama"),
               mhswa.getString("nrp"),
               mhswa.getString("kelas"),
               mhswa.getString("semester")
           });
       }
       tabel1.setModel(data);
   }catch (Exception e){
       JOptionPane.showMessageDialog(null,"ERROR \n Gagal Memuat KeDatabase \n Aktifkan Database Sebelum Memulai");
   }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel1;
    private javax.swing.JButton tbcari;
    private javax.swing.JButton tbdelete;
    private javax.swing.JButton tbrefres;
    private javax.swing.JButton tbsimpan;
    private javax.swing.JButton tbupdate;
    private javax.swing.JTextField tfkelas;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnrp;
    private javax.swing.JTextField tfsemester;
    // End of variables declaration//GEN-END:variables

}
